### ISSUE TITLE
Spec always fails the first time, succeeds the second

### ISSUE THREAD

**Issue by brchristian** [spree-contrib/spree_tax_cloud#11]
Curiously, every time I run a fresh `be rake test_app & be rspec spec` I see the following error.

    Failure/Error: Unable to find matching line from backtrace
     TaxCloud::Errors::MissingConfigOption:
       
       Problem:
         Missing configuration option: api_login_id.
       Summary:
         A configuration option was not provided when configuration TaxCloud.
       Resolution:
         Review your `TaxCloud.configure` code. Are you using an environment variable that has not been set?
 
However, whenever I run `be rspec spec` a _second_ time, everything is fine and the specs pass.

@JDutil Any idea what might be causing that? Am I defining the config variables wrong or something?

**Comment by brchristian** [comment]
@BenMorganIO Did you encounter this issue in your work on `spree_tax_cloud`, and do you have any ideas about what might be going on here?

**Comment by BenMorganIO** [comment]
I don't think I experienced this. I ended up not really having to work much with the specs. :(
