### ISSUE TITLE
required spree version

### ISSUE THREAD

**Issue by westlakem** [spree-contrib/spree_tax_cloud#22]
In your gemspec you have

s.add_dependency 'spree_core', '~> 3.0.0.beta'

but in your versionFile you have

'2.4.x' => { branch: master}

**Comment by brchristian** [comment]
@westlakem Good catch - thanks!

**Comment by JDutil** [comment]
The Versionfile is no longer used by https://spreecommerce.com/extensions which now simply checks for the appropriate stable branch i.e. 3-0-stable 2-4-stable etc...  I found the Versionfile useful for people who knew what it meant, but many people don't & it's not used by much anymore.  You may want to just remove it altogether unless you want to continue maintaining it for the people who do read them.

**Comment by brchristian** [comment]
@JDutil Ah, thanks -- I didn't realize it was no longer in use. Removed it on the `master` branch.
