### ISSUE TITLE
Tax amount of 0.0 returned

### ISSUE THREAD

**Issue by RoryMacDonald** [spree-contrib/spree_tax_cloud#24]
We're running into an issue in which we're having 0.0 returned as the tax amount. This doesn't seem correct. We're running 2-4-stable of spree and tax_cloud. We've got multiple stock locations and tax rates setup as per the instructions.

Any thoughts?

`gem 'spree',                      github: 'spree/spree', branch: '2-4-stable'

gem 'spree_tax_cloud',            github: 'spree-contrib/spree_tax_cloud', branch: '2-4-stable'
`

![screen shot 2015-04-28 at 22 58 24](https://cloud.githubusercontent.com/assets/72051/7381950/1f32ba50-ee01-11e4-92a9-ae82b2cc79c9.png)

**Comment by brchristian** [comment]
The specs appear to be passing, so for the moment I'm going to brainstorm
causes related to your app config.

How are your Zones and TaxCategories set up? I believe Spree would be
checking that the items match both before it would make a call to TaxCloud.

**Comment by RoryMacDonald** [comment]
This is what I thought initially but did you see the screenshot I attached?

When we create an order then use Rails console to call the TaxCloud code
directly, it returns 0.0 - this code is bypassing both Zones & TaxRates.

Do you know if the TaxCloud API return 0.0 if running in local dev mode?
We've got an environment called localhost setup in TC, thought it might be
related to this?

On Tuesday, 28 April 2015, brchristian <notifications@github.com> wrote:

> The specs appear to be passing, so for the moment I'm going to brainstorm
> causes related to your app config.
>
> How are your Zones and TaxCategories set up? I believe Spree would be
> checking that the items match both before it would make a call to TaxCloud.
>
>
>
> On Tue, Apr 28, 2015 at 3:52 PM, Rory MacDonald <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > We're running into an issue in which we're having 0.0 returned as the tax
> > amount. This doesn't seem correct. We're running 2-4-stable of spree and
> > tax_cloud. We've got multiple stock locations and tax rates setup as per
> > the instructions.
> >
> > Any thoughts?
> >
> > `gem 'spree', github: 'spree/spree', branch: '2-4-stable'
> >
> > gem 'spree_tax_cloud', github: 'spree-contrib/spree_tax_cloud', branch:
> > '2-4-stable'
> > `
> >
> > [image: screen shot 2015-04-28 at 22 58 24]
> > <
> https://cloud.githubusercontent.com/assets/72051/7381950/1f32ba50-ee01-11e4-92a9-ae82b2cc79c9.png
> >
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <https://github.com/spree-contrib/spree_tax_cloud/issues/24>.
> >
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/spree-contrib/spree_tax_cloud/issues/24#issuecomment-97253109>
> .
>


-- 
-- 
Rory MacDonald
Founder & Director

T. +44 (0)203 397 7847
M. +44 (0)77898 13756
W. www.madetech.co.uk

**Comment by brchristian** [comment]
I just spun up a new default Spree 2.4 store to see if I could replicate, but it looks fine for me. Hmm.

Let's see if we can diagnose.

Can you show me the console output for:

```ruby
Spree::TaxRate.all

Spree::TaxRate.all.collect { |tr| tr.tax_category }
order.products.collect { |p| p.tax_category }

Spree::TaxRate.all.collect { |tr| tr.zone }
order.tax_zone

Spree::TaxRate.match(order.tax_zone)
Spree::TaxRate.match(order.tax_zone).collect { |tr| tr.calculator }
```

Let's see if the culprit shows up there. Let me know what you get from the above.

**Comment by brchristian** [comment]
@RoryMacDonald Any success re above?

**Comment by RoryMacDonald** [comment]
Managed to resolve this - It was because we were using a MA address, which isn't supported via TaxCloud.

**Comment by RoryMacDonald** [comment]
We can close this

**Comment by techverx** [comment]
@RoryMacDonald, i am having the same problem let me show you the result of the commands which you mentioned in your above comment.

    Spree::TaxRate.all

    #<ActiveRecord::Relation [#<Spree::TaxRate id: 1, amount: #<BigDecimal:b0c0a70,'0.0',9(18)>, zone_id: 2, tax_category_id: 1, included_in_price: false, created_at: "2015-10-21 14:50:35", updated_at: "2015-10-21 14:56:21", name: "North America", show_rate_in_label: false, deleted_at: nil>]> 


    Spree::TaxRate.all.collect { |tr| tr.tax_category }

    [#<Spree::TaxCategory id: 1, name: "Clothing", description: "", is_default: true, deleted_at: nil, created_at: "2015-10-21 14:50:34", updated_at: "2015-10-21 15:36:32", tax_code: "">]

    order.products.collect { |p| p.tax_category }

    [#<Spree::TaxCategory id: 1, name: "Clothing", description: "", is_default: true, deleted_at: nil, created_at: "2015-10-21 14:50:34", updated_at: "2015-10-21 15:36:32", tax_code: "">] 

    Spree::TaxRate.all.collect { |tr| tr.zone }

    [#<Spree::Zone id: 2, name: "North America", description: "USA + Canada", default_tax: false, zone_members_count: 2, created_at: "2015-10-21 14:50:11", updated_at: "2015-10-21 14:50:11">]

    order.tax_zone

    #<Spree::Zone id: 2, name: "North America", description: "USA + Canada", default_tax: false, zone_members_count: 2, created_at: "2015-10-21 14:50:11", updated_at: "2015-10-21 14:50:11"> 

    Spree::TaxRate.match(order.tax_zone)

    [#<Spree::TaxRate id: 1, amount: #<BigDecimal:abc5728,'0.0',9(18)>, zone_id: 2, tax_category_id: 1, included_in_price: false, created_at: "2015-10-21 14:50:35", updated_at: "2015-10-21 14:56:21", name: "North America", show_rate_in_label: false, deleted_at: nil>]

    Spree::TaxRate.match(o.tax_zone).collect { |tr| tr.calculator }

    [#<Spree::Calculator::TaxCloudCalculator id: 7, type: "Spree::Calculator::TaxCloudCalculator", calculable_id: 1, calculable_type: "Spree::TaxRate", created_at: "2015-10-21 14:56:21", updated_at: "2015-10-21 14:56:21", preferences: {}>] 
    2.1.1 :016 > 

Can you help me on this ?

**Comment by brchristian** [comment]
@techverx I'll see if I can be of help.

The first thing I notice is that the TaxCategory is "Clothing", which I believe is a Spree default, but just so you know, TaxCloud does all its own product categorization, so you really want the TaxCategory to apply to everything, and probably want to give it a generic name like "Taxable" or something.

The only other thing that comes to mind is simply that there are of course many states in the US that don't charge sales tax. What's the address associated with this order?

**Comment by techverx** [comment]
Here is the address 

address : 1200-1298 Tulane Ave, New Orleans, LA 70112, USA

city: new orleand

zipcode: 70112

state : Louisiana

**Comment by brchristian** [comment]
I'm using the TaxCloud website and seeing a 0.0% rate for that address:

![screen shot 2015-11-02 at 7 43 23 pm](https://cloud.githubusercontent.com/assets/2460418/10900865/1920c1a2-819a-11e5-8b91-dad4438dabc4.png)

This seems strange, because Googling around shows the rate to be 9% (5% local + 4% state).

This may be a problem with the TaxCloud API itself.

I'll mention it to the TaxCloud via their contact email, and encourage you to do the same. Hope that's helpful.

**Comment by RoryMacDonald** [comment]
I believe that some states are not supported by TaxCloud and it returns 0%
for these. Could this be one of the not-supported states?

On Tuesday, 3 November 2015, brchristian <notifications@github.com> wrote:

> I'm using the TaxCloud website and seeing a 0.0% rate for that address:
>
> [image: screen shot 2015-11-02 at 7 43 23 pm]
> <https://cloud.githubusercontent.com/assets/2460418/10900865/1920c1a2-819a-11e5-8b91-dad4438dabc4.png>
>
> This seems strange, because Googling around shows the rate to be 9% (5%
> local + 4% state).
>
> This may be a problem with the TaxCloud API itself.
>
> I'll mention it to the TaxCloud via their contact email, and encourage you
> to do the same. Hope that's helpful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spree-contrib/spree_tax_cloud/issues/24#issuecomment-153232622>
> .
>


-- 
-- 
Rory MacDonald
Founder & Director
-

T. +44 (0)203 397 7847
M. +44 (0)77898 13756
W. www.madetech.com

**Comment by brchristian** [comment]
That's possible, although I'm not certain. I'll update this thread when I
hear word back from TaxCloud support (likely tomorrow).

**Comment by brchristian** [comment]
@techverx @RoryMacDonald TaxCloud reminded me that the way sales tax is set up in the US, you might only need to charge for state sales tax if you have operations in that state. So, if you only operate in California, you might only need to charge sales tax to orders that ship to CA addresses. This may be the issue you're experiencing. I recommend talking directly with TaxCloud support and making sure your account is configured properly. Either 0.0% will be correct for Louisiana addresses, or you'll need to configure TaxCloud to be charging tax for addresses in that state. Hope that's helpful.
