### ISSUE TITLE
Did not see tax on products on checkout page and cart page.

### ISSUE THREAD

**Issue by qubaish-techverx** [spree-contrib/spree_tax_cloud#29]
I integrated the spree_tax_cloud gem and follow the steps that are written

1) Taxable Category
2) USA Zone 
3) Tax rate with these characteristics

Name: Sales Tax (This label will be visible to users during the checkout process)
Zone: USA (Note that TaxCloud is only designed for United States sales tax)
Rate: 0.0 (Note that the actual rates will be applied by the calculator)
Tax Category: Taxable
Included in Price: False (US taxes are 'additional' rather than 'included')
Show Rate in Label: False (We will not display the static rate, which is left at 0%)
Calculator: Tax Cloud

4) Add taxable category on product 
5) Provide tax cloud api thing. 
6) Correct the stock location 

After all doing this i solved my errors .. but now i have not seen any tax calculation in my whole checkout process.. Please help me what i did wrong or what i miss steps . 

Thanks

**Comment by brchristian** [comment]
@qubaish-techverx Hmm, let's see. What is the address being provided on these orders?

**Comment by brchristian** [comment]
@qubaish-techverx I am assuming that this is similar to an issue that other users have experienced where sales tax collection was not enabled for that state. (Depending on your business, you may not need to collect tax in every state.) To enable sales tax to be charged in specific states, log in to your TaxCloud account and go to `Your Account` >> `Tax States`.

I've updated the extension Readme to include this information, as I think several users have been running in to this issue in getting their TaxCloud accounts set up.

I'm going to close this issue as I haven't heard any more from you, but if you are still having issues and the above doesn't fix it, you are welcome to reopen it. Hope this is helpful!
